= Aansluitingenregister
:table-caption!:
:table-grid: rows
:parent: Aansluitingenregister

_Het aansluitingenregister bevat alle elektriciteits- en gasaansluitingen in Nederland._

Het aansluitingenregister wordt gezamenlijk beheerd door de netbeheerders en bevat zowel fysieke als administratieve gegevens over aansluitingen. Het register is essentieel voor de werking van de energiemarkt omdat het de basis vormt voor processen zoals leverancierswisselingen, verhuizingen en facturatie.

De verplichting tot het bijhouden van het aansluitingenregister is vastgelegd in de Informatiecode elektriciteit en gas, vastgesteld door de Autoriteit Consument en Markt (ACM).

.Zie ook
[%collapsible]
====
* https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=2&paragraaf=2.1&z=2025-01-01&g=2025-01-01[`https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=2&paragraaf=2.1&z=2025-01-01&g=2025-01-01`]
====
image::aansluitingenregister.drawio.svg[id=conceptual-model]

xref::attachment$aansluitingenregister.linkml.yml[LinkML-broncode]




[[aangeslotene]]
== Aangeslotene

_https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/aangeslotene[`nbnl:aangeslotene`]_

Aangeslotenen worden niet uniek geïdentificeerd. Daarom gaat het hier om een gegevensgroep bij een aansluiting, niet om een zelfstandige entiteit.






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| geboortedatum
| <<tekst,Tekst>> [0..1]
a| _datum van de bevalling waarbij de aangeslotene is geboren_

.Zie ook
[%collapsible]
====
* https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=3&paragraaf=3.3&sub-paragraaf=3.3.1&artikel=3.3.1.1&z=2023-06-28&g=2023-06-28[`https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=3&paragraaf=3.3&sub-paragraaf=3.3.1&artikel=3.3.1.1&z=2023-06-28&g=2023-06-28`]
====
| KVK-nummer
| <<tekst,Tekst>> [0..1]
a| _identificatie van de maatschappelijke activiteit van de aangeslotene in het Handelsregister_

.Zie ook
[%collapsible]
====
* https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=3&paragraaf=3.3&sub-paragraaf=3.3.1&artikel=3.3.1.1&z=2023-06-28&g=2023-06-28[`https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=3&paragraaf=3.3&sub-paragraaf=3.3.1&artikel=3.3.1.1&z=2023-06-28&g=2023-06-28`]
====
| naam
| <<tekst,Tekst>> [1]
a| _naam van een organisatie of de achternaam (zonder tussenvoegsel) van een natuurlijk persoon_
| tussenvoegsel
| <<tekst,Tekst>> [0..1]
a| _verzameling van een of meer voorzetsels en/of lidwoorden die aan de achternaam van een aangeslotene vooraf gaat en daarmee gezamenlijk de volledige achternaam vormt_

.Zie ook
[%collapsible]
====
* https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=2&paragraaf=2.9&sub-paragraaf=2.9.2&artikel=2.9.2.1&z=2022-12-20&g=2022-12-20[`https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=2&paragraaf=2.9&sub-paragraaf=2.9.2&artikel=2.9.2.1&z=2022-12-20&g=2022-12-20`]
====
| voorletters
| <<tekst,Tekst>> [0..1]
a| _verzameling letters die wordt gevormd door de eerste letter van alle in volgorde voorkomende voornamen van een aangeslotene_

.Zie ook
[%collapsible]
====
* https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=2&paragraaf=2.9&sub-paragraaf=2.9.2&artikel=2.9.2.1&z=2022-12-20&g=2022-12-20[`https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=2&paragraaf=2.9&sub-paragraaf=2.9.2&artikel=2.9.2.1&z=2022-12-20&g=2022-12-20`]
====

|===



.Relaties
[%autowidth.stretch]
|===
| Aangeslotene is ... | Omschrijving

| pass:[<span title="Maakt deel uit van de identificatie">🔑</span>&nbsp;]beschikker over (Aansluiting) <<aansluiting,Aansluiting>> [0..1 → 1]
a| 

|===






[[aansluiting]]
== Aansluiting

_https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/aansluiting[`nbnl:aansluiting`]_

Nauwer: https://nbility-model.github.io/NBility-business-capabilities-Archi/aansluiting[`nbility:aansluiting`]

Een koppeling met een gesloten distributiesysteem wordt in dit register beschouwd als aansluiting als de beheerder geen gebruik maakt van het elektronische berichtenverkeer ten behoeve van het faciliteren van derdentoegang ([artikel 2.4, vierde lid van de Netcode elektriciteit](https://wetten.overheid.nl/jci1.3:c:BWBR0037940&hoofdstuk=2&paragraaf=2.1&artikel=2.4&z=2023-04-01&g=2023-04-01)).






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| pass:[<span title="Maakt deel uit van de identificatie">🔑</span>&nbsp;]EAN-code
| <<ean-18,EAN-18>> [1]
a| _unieke cijfercombinatie volgens de Europese Artikelnummer-standaard_
| energiedrager
| <<energiedrager,Energiedrager>> [0..1]
a| _https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/energiedrager[`nbnl:energiedrager`]_
| gecontracteerde transportcapaciteit
| <<tekst,Tekst>> [0..1]
a| _https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/gecontracteerde-transportcapaciteit[`nbnl:gecontracteerde-transportcapaciteit`]_
| grootte
| <<groot-of-klein,Groot of klein>> [1]
a| _aanduiding van het formaat van de aansluiting op basis van de gewenste aansluitcapaciteiten van de overdrachtspunten_

Validatie: als de gewenste aansluitcapaciteit van een van de overdrachtspunten 'groot' is of een geheel getal dan 'groot' anders 'klein'.
| marktsegment
| <<marktsegment,Marktsegment>> [1]
a| _aanduiding van de categorie waartoe de aansluiting behoort, te weten kleinverbruikaansluiting of grootverbruikaansluiting_

Een aansluiting met een kleine capaciteit kan onder voorwaarden worden beschouwd als grootverbruikaansluiting, bijvoorbeeld als het een aansluiting betreft op een gesloten distributiesysteem of een aansluiting zoals bedoeld in [artikel 1, lid 2 of 3 van de Elektriciteitswet 1998](https://wetten.overheid.nl/jci1.3:c:BWBR0009755&hoofdstuk=1&paragraaf=1&artikel=1&z=2022-10-01&g=2022-10-01).

.Zie ook
[%collapsible]
====
* https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=2&paragraaf=2.1&artikel=2.1.3&z=2022-05-18&g=2022-05-18[`https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=2&paragraaf=2.1&artikel=2.1.3&z=2022-05-18&g=2022-05-18`]
* https://wetten.overheid.nl/jci1.3:c:BWBR0037938&hoofdstuk=1&artikel=1.1&z=2022-11-25&g=2022-11-25[`https://wetten.overheid.nl/jci1.3:c:BWBR0037938&hoofdstuk=1&artikel=1.1&z=2022-11-25&g=2022-11-25`]
====
| uitsluitend elektriciteitsproductie-eenheden
| <<waar-of-onwaar,Waar of onwaar>> [1]
a| _indicatie of achter een aansluiting zich uitsluitend elektriciteitsproductie-eenheden bevinden en geen ander verbruik dan het eigen verbruik van de desbetreffende elektriciteitsproductie-eenheden_

Ook wel bekend als 'zuivere teruglevering'.

.Zie ook
[%collapsible]
====
* https://wetten.overheid.nl/jci1.3:c:BWBR0037951&hoofdstuk=3&paragraaf=3.7&artikel=3.7.13.b&z=2022-05-18&g=2022-05-18[`https://wetten.overheid.nl/jci1.3:c:BWBR0037951&hoofdstuk=3&paragraaf=3.7&artikel=3.7.13.b&z=2022-05-18&g=2022-05-18`]
====
| weekmax
| <<waar-of-onwaar,Waar of onwaar>> [0..1]
a| _indicatie of de kWmax per week gemeten moet worden_

.Zie ook
[%collapsible]
====
* https://wetten.overheid.nl/jci1.3:c:BWBR0037951&hoofdstuk=3&paragraaf=3.7&artikel=3.7.5a&z=2022-05-18&g=2022-05-18[`https://wetten.overheid.nl/jci1.3:c:BWBR0037951&hoofdstuk=3&paragraaf=3.7&artikel=3.7.5a&z=2022-05-18&g=2022-05-18`]
====

|===



.Relaties
[%autowidth.stretch]
|===
| Aansluiting is ... | Omschrijving

| deel van (Netgebied) <<netgebied,Netgebied>> [0..* → 0..1]
a| 

|===






[[allocatiepunt]]
== Allocatiepunt

_punt waar invoeding, onttrekking of verbruik van elektriciteit of gas wordt toegerekend aan een marktdeelnemer_






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| pass:[<span title="Maakt deel uit van de identificatie">🔑</span>&nbsp;]EAN-code
| <<ean-18,EAN-18>> [1]
a| _unieke cijfercombinatie volgens de Europese Artikelnummer-standaard_

|===








[[allocatiepunt-bij-aansluiting]]
== Allocatiepunt bij aansluiting

_allocatiepunt toegekend aan een aansluiting_

Specialisatie van <<allocatiepunt,Allocatiepunt>>








.Relaties
[%autowidth.stretch]
|===
| Allocatiepunt bij aansluiting is ... | Omschrijving

| bij (Aansluiting) <<aansluiting,Aansluiting>> [1..* → 1]
a| 

|===






[[allocatiepunt-bij-netgebied]]
== Allocatiepunt bij netgebied

_allocatiepunt toegekend aan een netgebied_

Specialisatie van <<allocatiepunt,Allocatiepunt>>








.Relaties
[%autowidth.stretch]
|===
| Allocatiepunt bij netgebied is ... | Omschrijving

| bij (Netgebied) <<netgebied,Netgebied>> [1..* → 1]
a| 

|===






[[netgebied]]
== Netgebied

_aaneengesloten en samenhangend deel van een energienet van één netbeheerder, waarbinnen de processen allocatie en reconciliatie plaatsvinden_

.Zie ook
[%collapsible]
====
* https://wetten.overheid.nl/jci1.3:c:BWBR0037938&hoofdstuk=1&artikel=1.1&z=2022-11-25&g=2022-11-25[`https://wetten.overheid.nl/jci1.3:c:BWBR0037938&hoofdstuk=1&artikel=1.1&z=2022-11-25&g=2022-11-25`]
* https://wetten.overheid.nl/jci1.3:c:BWBR0037923&hoofdstuk=1&artikel=1.1&z=2021-06-01&g=2021-06-01[`https://wetten.overheid.nl/jci1.3:c:BWBR0037923&hoofdstuk=1&artikel=1.1&z=2021-06-01&g=2021-06-01`]
====






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| pass:[<span title="Maakt deel uit van de identificatie">🔑</span>&nbsp;]EAN-code
| <<ean-18,EAN-18>> [1]
a| _unieke cijfercombinatie volgens de Europese Artikelnummer-standaard_

|===








[[overdrachtspunt]]
== Overdrachtspunt

_https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/overdrachtspunt[`nbnl:overdrachtspunt`]_






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| pass:[<span title="Maakt deel uit van de identificatie">🔑</span>&nbsp;]EAN-code
| <<ean-18,EAN-18>> [1]
a| _unieke cijfercombinatie volgens de Europese Artikelnummer-standaard_

|===



.Relaties
[%autowidth.stretch]
|===
| Overdrachtspunt is ... | Omschrijving

| deel van (Aansluiting) <<aansluiting,Aansluiting>> [1..* → 1]
a| 

|===






'''
[discrete]
== Waardesoorten

[%autowidth.stretch]
|===
| Waardesoort | Omschrijving | Gebaseerd op | Patroon

| [[datum]]Datum
a| _kalenderdatum, zonder tijdsaanduiding_
| datum
| 

| [[ean-18]]EAN-18
a| _Europees artikelnummer van achttien cijfers_
| <<tekst,Tekst>>
| `^[0-9]{18}$`

| [[geheel-getal]]Geheel getal
a| _getal zonder decimalen_
| <<int,int>>
| 

| [[getal]]Getal
a| _voorstelling van een hoeveelheid_
| reëel getal
| 

| [[tekst]]Tekst
a| _aanduiding bedoeld voor mensen, zonder vaste structuur of betekenis_
| <<str,str>>
| 

| [[tijdsduur]]Tijdsduur
a| _lengte van een tijdsinterval, bijvoorbeeld een uur of een dag_
| <<duration,duration>>
| 

| [[tijdstip]]Tijdstip
a| _exacte aanduiding van datum en tijd, inclusief eventueel tijdzone-informatie_
| datum en tijd
| 

| [[uri]]URI
a| _uniforme aanduiding van een externe of interne bron_
| URI
| 

| [[waar-of-onwaar]]Waar of onwaar
a| _binaire aanduiding die aangeeft of een propositie of kenmerk van toepassing is (waar) of niet van toepassing is (onwaar)_
| <<bool,bool>>
| 

|===





'''
[discrete]
== Waardelijsten


[[energiedrager]]
[discrete]
=== Energiedrager



[%autowidth.stretch]
|===
| Waarde | Omschrijving

| elektriciteit
a| 
| gas
a| 
| waterstof
a| 
|===




[[groot-of-klein]]
[discrete]
=== Groot of klein



[%autowidth.stretch]
|===
| Waarde | Omschrijving

| groot
a| 
| klein
a| 
|===




[[marktsegment]]
[discrete]
=== Marktsegment



[%autowidth.stretch]
|===
| Waarde | Omschrijving

| grootverbruikaansluiting
a| 
| kleinverbruikaansluiting
a| 
|===

