= Installatieregister
:table-caption!:
:table-grid: rows
:parent: Installatieregister

_Het installatieregister bevat informatie over installatie-eenheden achter aansluitingen op het energienet, voor zover deze door of namens aangeslotenen zijn aangemeld bij de netbeheerder._

NBility: https://nbility-model.github.io/NBility-business-capabilities-Archi/?view=id-8becf2d90261476faa9d53240e6cf2c8[C.6.2.2. Installaties achter aansluitingen beheren]

.Zie ook
[%collapsible]
====
* https://wetten.overheid.nl/jci1.3:c:BWBR0037940&hoofdstuk=13&paragraaf=13.1&z=2025-09-01&g=2025-09-01[nce:hoofdstuk=13&paragraaf=13.1&z=2025-09-01&g=2025-09-01]
====

image::installatieregister.drawio.svg[id=conceptual-model]

xref::attachment$installatieregister.linkml.yml[LinkML-broncode]






[[Beveiligingsinstelling]]
== Beveiligingsinstelling

_manier waarop wordt beschermd tegen storingen_

Breder: https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/installatie[begrip:installatie]

Tijdlijnen: registratie






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| afschakeltijd
| reëel getal{nbsp}(ms) [1]
a| _tijd om iets buiten werking te stellen_
| eenheid
| <<local:Eenheid-onregelmatigheid,Eenheid onregelmatigheid>> [1]
a| _maat waarin een grootheid numeriek kan worden uitgedrukt_
| pass:[<span title="Maakt deel uit van de identificatie">🔑</span>&nbsp;]onregelmatigheid
| <<local:Onregelmatigheid,Onregelmatigheid>> [1]
a| _afwijking van de normale bedrijfsomstandigheden_
| waarde
| reëel getal [1]
a| 

|===



.Relaties
[%autowidth.stretch]
|===
| Beveiligingsinstelling is ... | Omschrijving

| pass:[<span title="Maakt deel uit van de identificatie">🔑</span>&nbsp;]bij https://modellen.netbeheernederland.nl/aansluitingenregister#Overdrachtspunt[Overdrachtspunt] (Aansluitingenregister) [* → 1]
a| 

|===






[[Conformiteitscertificaat]]
== Conformiteitscertificaat

_door een erkende certificerende instantie verstrekt document voor apparatuur die wordt gebruikt door een elektriciteitsproductie-eenheid, verbruikseenheid, distributiesysteem, verbruikersinstallatie of HVDC-systeem_ (zie https://eur-lex.europa.eu/legal-content/NL/TXT/?uri=CELEX:32016R0631[celex:32016R0631])

Breder: https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/installatie[begrip:installatie]

Tijdlijnen: registratie






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| pass:[<span title="Maakt deel uit van de identificatie">🔑</span>&nbsp;]fabrikant
| tekst [1]
a| _bedrijf dat industrieel goederen vervaardigt_
| pass:[<span title="Maakt deel uit van de identificatie">🔑</span>&nbsp;]typeaanduiding
| tekst [1]
a| _naam die door een fabrikant aan een reeks producten met vergelijkbare eigenschappen wordt gegeven_

|===








[[Elektriciteitsinstallatie-eenheid]]
== Elektriciteitsinstallatie-eenheid

_ondeelbaar geheel van elektrisch materieel en leidingen die samen elektrische energie kunnen verbruiken, opwekken, opslaan, laden of ontladen_ (zie https://eur-lex.europa.eu/legal-content/NL/TXT/?uri=CELEX:32016R0631[celex:32016R0631])

Breder: https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/installatie[begrip:installatie]

Tijdlijnen: registratie, levensduur (moment van inbedrijfname, moment van uitbedrijfname)






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| pass:[<span title="Maakt deel uit van de identificatie">🔑</span>&nbsp;]EAN-code
| tekst [1]
a| _unieke cijfercombinatie volgens de Europese Artikelnummer-standaard_

.Zie ook
[%collapsible]
====
* https://wetten.overheid.nl/jci1.3:c:BWBR0037940&hoofdstuk=2&paragraaf=2.1&artikel=2.4&z=2024-07-05&g=2024-07-05[nce:hoofdstuk=2&paragraaf=2.1&artikel=2.4&z=2024-07-05&g=2024-07-05]
====
| kortsluitbijdrage
| tekst [0..1]
a| _hoeveelheid stroom die een elektrische installatie levert aan een kortsluiting in het elektriciteitsnet_
| maximumcapaciteit voor afname
| reëel getal{nbsp}(kW) [0..1]
a| _maximaal continu werkzame vermogen dat een elektricitsinstallatie-eenheid kan verbruiken, als gespecificeerd in de aansluitovereenkomst of overeengekomen tussen de netbeheerder en de eigenaar van de installatie_

Breder: https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/maximumcapaciteit[begrip:maximumcapaciteit]

Validatieregel: verplicht bij opslageenheid en laadeenheid. Verplicht leeg bij productie-eenheid.
| maximumcapaciteit voor invoeding
| reëel getal{nbsp}(kW) [0..1]
a| _maximaal continu werkzame vermogen dat een elektriciteitsinstallatie-eenheid kan produceren, verminderd met de vraag die uitsluitend verband houdt met het bedrijf van die eenheid zelf en die niet voor het energienet beschikbaar is, als gespecificeerd in de aansluitovereenkomst of overeengekomen tussen de netbeheerder en de eigenaar van de installatie_

Breder: https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/maximumcapaciteit[begrip:maximumcapaciteit]

Validatieregel: verplicht bij productie-eenheid en opslageenheid.
| totale vermogen omvormers
| reëel getal{nbsp}(MW) [0..1]
a| _som van de vermogens van alle bij de elektriciteitinstallatie-eenheid behorende omvormers_

⚠ Bij type A staat kW op het formulier, bij type B, C en D, MW. Is het oké om in het register enkel MW (of enkel kW) te hanteren?
| type
| <<local:Type-elektriciteitsinstallatie-eenheid,Type elektriciteitsinstallatie-eenheid>> [1]
a| _classificatie op basis van maximumcapaciteit en spanning op het overdrachtspunt_ (zie https://eur-lex.europa.eu/legal-content/NL/TXT/?uri=CELEX:32016R0631[celex:32016R0631])
| typeaanduiding
| tekst [1]
a| _naam die door een fabrikant aan een reeks producten met vergelijkbare eigenschappen wordt gegeven_

|===



.Relaties
[%autowidth.stretch]
|===
| Elektriciteitsinstallatie-eenheid is ... | Omschrijving

| achter https://modellen.netbeheernederland.nl/aansluitingenregister#Overdrachtspunt[Overdrachtspunt] (Aansluitingenregister) [* → 1]
a| 

|===






[[Elektriciteitslaadeenheid]]
== Elektriciteitslaadeenheid

_https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/elektriciteitslaadeenheid[begrip:elektriciteitslaadeenheid]_

Specialisatie van <<Elektriciteitsinstallatie-eenheid,Elektriciteitsinstallatie-eenheid>>

⚠ Het is nog niet duidelijk hoe laadpunten gegroepeerd moeten worden in laadeenheden. Dit heeft namelijk direct effect op het type (A, B, C, D) en daarmee de aansluitvoorwaarden en verplichtingen die gelden voor de aangeslotene. Niet elke laadlocatie bestaat uit laadpalen, denk aan bogen, muren, etc.













[[Elektriciteitsopslageenheid]]
== Elektriciteitsopslageenheid

_https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/elektriciteitsopslageenheid[begrip:elektriciteitsopslageenheid]_

Specialisatie van <<Elektriciteitsinstallatie-eenheid,Elektriciteitsinstallatie-eenheid>>






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| energieherkomst
| <<local:Energieherkomst,Energieherkomst>> [1]
a| _aanduiding die aangeeft of de opgeslagen energie afkomstig is uit het energienet, die installatie of beide_
| maximaal bruikbare hoeveelheid energie
| reëel getal{nbsp}(kWh) [1]
a| _hoeveelheid elektrische energie die maximaal in een elektriciteitsopslageenheid kan worden geïnjecteerd en daaruit kan worden onttrokken voor het energienet_

|===








[[Elektriciteitsproductie-eenheid]]
== Elektriciteitsproductie-eenheid

_https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/elektriciteitsproductie-eenheid[begrip:elektriciteitsproductie-eenheid]_

Specialisatie van <<Elektriciteitsinstallatie-eenheid,Elektriciteitsinstallatie-eenheid>>






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| primaire energiebron
| <<local:Energiebron,Energiebron>> [1]
a| _stof, object of natuurlijke plaats waaruit de meeste energie wordt gehaald_

.Zie ook
[%collapsible]
====
* https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=2&paragraaf=2.1&artikel=2.1.5&z=2025-01-01&g=2025-01-01[iceg:hoofdstuk=2&paragraaf=2.1&artikel=2.1.5&z=2025-01-01&g=2025-01-01]
====
| totale vermogen opwekkingseenheden
| reëel getal{nbsp}(MW) [0..1]
a| _som van de vermogens van alle bij de elektriciteitsproductie-eenheid behorende opwekkingseenheden_

Alhoewel artikel 13.1 van de Netcode elektriciteit het totale vermogen van de elektriciteitsproductie-installatie noemt, gaat dit register uit van het totale vermogen per elektriciteitsprodcutie-eenheid.

⚠ Bij type A staat kW op het formulier, bij type B, C en D, MW. Is het oké om in het register enkel MW (of enkel kW) te hanteren?
| x-coördinaat
| reëel getal{nbsp}(m) [0..1]
a| _oost-westpositie van een punt in het Rijksdriehoeksstelsel (RD)_
| y-coördinaat
| reëel getal{nbsp}(m) [0..1]
a| _noord-zuidpositie van een punt in het Rijksdriehoeksstelsel (RD)_

|===








[[GCvO-installatie]]
== GCvO-installatie

_productie-installatie of een op grond van de criteria uit artikel 24 van de Regeling garanties van oorsprong en certificaten van oorsprong afgebakend deel daarvan, die of dat op grond van artikel 16, eerste lid, onderdeel h, van de Elektriciteitswet 1998, of artikel 10, vijfde lid, onderdeel c, van de Gaswet, wordt aangemerkt als een installatie voor de productie van energie als bedoeld in artikel 73, eerste lid van de Elektriciteitswet 1998, of artikel 66i, eerste lid van de Gaswet_ (zie bge:z=2025-05-08&g=2025-05-08[bge:z=2025-05-08&g=2025-05-08])

Breder: https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/installatie[begrip:installatie]

Tijdlijnen: registratie, levensduur (moment van inbedrijfname, moment van uitbedrijfname)

.Zie ook
[%collapsible]
====
* https://wetten.overheid.nl/jci1.3:c:BWBR0035971&z=2025-04-01&g=2025-04-01[rgcvo:z=2025-04-01&g=2025-04-01]
====






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| pass:[<span title="Maakt deel uit van de identificatie">🔑</span>&nbsp;]EAN-code
| tekst [1]
a| _unieke cijfercombinatie volgens de Europese Artikelnummer-standaard_
| energiedrager
| <<local:Energiedrager,Energiedrager>> [1]
a| _https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/energiedrager[begrip:energiedrager]_
| hoogrenderende warmtekrachtkoppeling
| waar of onwaar [0..1]
a| _geeft aan of sprake is van een installatie voor hoogrenderende warmtekrachtkoppeling (HR-WKK)_
| primaire energiebron
| tekst [0..1]
a| _stof, object of natuurlijke plaats waaruit de meeste energie wordt gehaald_
| subsidie
| waar of onwaar [0..1]
a| _geeft aan of de GCvO-installatie overheidssteun ontvangt of geniet_

|===



.Relaties
[%autowidth.stretch]
|===
| GCvO-installatie is ... | Omschrijving

| achter https://modellen.netbeheernederland.nl/aansluitingenregister#Allocatiepunt-bij-aansluiting[Allocatiepunt bij aansluiting] (Aansluitingenregister) [* → 1]
a| 

|===






[[Groep-van-omvormers]]
== Groep van omvormers

_verzameling elektronische apparaten die de invoerspanning van een bepaalde spanning naar een andere spanning kunnen omvormen of elektrische energie in energie van een andere frequentie_

Breder: https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/installatie[begrip:installatie]

De ACM beschouwt een groep zonnepanelen achter één omvormer, samen met die omvormer als een elektriciteitsproductie-eenheid (ACM/18/033360). Aanmeldformulieren van netbeheerders staan echter meer omvormers per eenheid toe.

Tijdlijnen: registratie






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| fabrikant
| tekst [1]
a| _bedrijf dat industrieel goederen vervaardigt_
| typeaanduiding
| tekst [1]
a| _naam die door een fabrikant aan een reeks producten met vergelijkbare eigenschappen wordt gegeven_

|===



.Relaties
[%autowidth.stretch]
|===
| Groep van omvormers is ... | Omschrijving

| deel van <<Elektriciteitsinstallatie-eenheid,Elektriciteitsinstallatie-eenheid>> [* → 1]
a| 

|===






[[Groep-van-opwekkingseenheden]]
== Groep van opwekkingseenheden

_verzameling apparaten binnen één elektriciteitsproductie-eenheid die elektrische energie opwekken en identieke kenmerken delen_

Breder: https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/installatie[begrip:installatie]

Tijdlijnen: registratie






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| aantal opwekkingseenheden
| geheel getal [1]
a| _hoeveelheid opwekkingseenheden in de groep_
| fabrikant
| tekst [1]
a| _bedrijf dat industrieel goederen vervaardigt_
| nominaal vermogen per opwekkingseenheid
| reëel getal{nbsp}(MVA) [0..1]
a| _door de fabrikant aangegeven maximale vermogen bij continu gebruik waarbij een maximaal rendement wordt behaald_
| nominale arbeidsfactor
| reëel getal [0..1]
a| _verhouding tussen het werkelijke vermogen en het schijnbare vermogen onder nominale bedrijfsomstandigheden_
| soort koppeling
| <<local:Soort-koppeling,Soort koppeling>> [1]
a| _manier waarop de opwekkingseenheden in de groep zijn gekoppeld met de rest van de installatie_
| subtransiënte reactantie
| tekst [0..1]
a| _kortstondige reactantie direct na een plotselinge storing zoals een kortsluiting, uitgedrukt in het per-unit systeem_
| typeaanduiding
| tekst [1]
a| _naam die door een fabrikant aan een reeks producten met vergelijkbare eigenschappen wordt gegeven_

|===



.Relaties
[%autowidth.stretch]
|===
| Groep van opwekkingseenheden is ... | Omschrijving

| deel van <<Elektriciteitsproductie-eenheid,Elektriciteitsproductie-eenheid>> [* → 1]
a| 

|===






[[Groep-van-windturbines]]
== Groep van windturbines

_verzameling van één of meer windturbines binnen één elektriciteitsproductie-eenheid die identieke kenmerken delen_

Specialisatie van <<Groep-van-opwekkingseenheden,Groep van opwekkingseenheden>>






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| ashoogte
| reëel getal{nbsp}(m) [0..1]
a| _verticale afstand in meters tot het middelpunt van de as waarop de wieken draaien_
| hoogtereferentie
| <<local:Hoogtereferentie,Hoogtereferentie>> [0..1]
a| _nulpunt van waaraf de ashoogte is gemeten_
| massatraagheidsmoment
| reëel getal{nbsp}(kg.m2) [0..1]
a| _maat voor de weerstand van de draaiende onderdelen tegen een verandering in hun rotatiesnelheid_

Traagheid (inertia) helpt het energienet te stabiliseren.

Dit betreft de fysieke vorm van traagheid, ter onderscheiding van de synthetische variant die door omvormers wordt geleverd.

|===








[[Groep-van-zonnepanelen]]
== Groep van zonnepanelen

_verzameling van één of meer zonnepanelen binnen één elektriciteitsproductie-eenheid die identieke kenmerken delen_

Specialisatie van <<Groep-van-opwekkingseenheden,Groep van opwekkingseenheden>>






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| azimut
| reëel getal{nbsp}(deg) [0..1]
a| _horizontale hoek, gemeten met de klok mee vanaf het geografische noorden - Bij een oost-westopstelling zijn er minimaal twee groepen, elk met een eigen azimut._
| hellingshoek
| reëel getal{nbsp}(deg) [0..1]
a| _hoek ten opzichte van het horizontale vlak_

|===










[[Soort-transformator]]
== Soort transformator

_verzameling transformatoren die een gemeenschappelijk karakter hebben_

Breder: https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/installatie[begrip:installatie]

Tijdlijnen: registratie






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| hoogste trap
| reëel getal{nbsp}(kV) [0..1]
a| _hoogste spanningsniveau van de regelschakelaar_
| laagste trap
| reëel getal{nbsp}(kV) [0..1]
a| _laagste spanningsniveau van de regelschakelaar_
| nominaal schijnbaar vermogen
| reëel getal{nbsp}(MVA) [1]
a| _maximale totale vermogen dat de transformator onder normale bedrijfsomstandigheden kan verwerken zonder overbelasting_
| nominale ijzer- of nullastverliezen
| reëel getal{nbsp}(kW) [1]
a| _verliezen in de transformator die optreden wanneer deze onder nominale spanning werkt, maar zonder belasting_
| nominale koper- of kortsluitverliezen
| reëel getal{nbsp}(kW) [1]
a| _warmteverliezen die optreden in de wikkelingen van de transformator wanneer deze onder nominale belasting werkt_
| nominale kortsluitspanning
| reëel getal{nbsp}(%) [1]
a| _spanning die nodig is om de volledige nominale stroom door de transformator te laten vloeien bij een kortsluiting op de uitgang, wanneer er geen belasting is_
| nominale spanning primair
| reëel getal{nbsp}(kV) [1]
a| _standaardspanning waarvoor de transformator is ontworpen om optimaal te functioneren aan de primaire zijde_
| nominale spanning secundair
| reëel getal{nbsp}(kV) [1]
a| _standaardspanning waarvoor de transformator is ontworpen om optimaal te functioneren aan de secundaire zijde_
| schakelgroep wikkelingen
| tekst [1]
a| _configuratie van de wikkelingen in de transformator die aangeeft hoe de spanningsfasen aan de primaire en secundaire zijde zich tot elkaar verhouden_

⚠ Beperken tot een bepaalde waardelijst met items zoals 'Dyn5'?
| stapgrootte
| reëel getal{nbsp}(kV) [0..1]
a| _spanningsverschil tussen opeenvolgende standen van de regelschakelaar_

|===



.Relaties
[%autowidth.stretch]
|===
| Soort transformator is ... | Omschrijving

| in <<Transformatoropstelling,Transformatoropstelling>> [* → 1]
a| 

|===






[[Transformatoropstelling]]
== Transformatoropstelling

_configuratie van transformatoren bedoeld voor de gezamenlijke werking rondom een bepaald overdrachtspunt_

Breder: https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/installatie[begrip:installatie]

Alhoewel artikel 13.1 van de Netcode elektriciteit vraagt om de transformatorgegevens van de gehele installatie, gaat dit register uit van de transformatorgegevens bij het overdrachtspunt waarachter de installatie-eenheid zich bevindt.

Tijdlijnen: registratie






.Eigenschappen
[%autowidth.stretch]
|===
| Eigenschap | Waardespecificatie | Omschrijving

| regelbaarheid
| <<local:Regelbaarheid,Regelbaarheid>> [0..1]
a| _aanduiding of de regelschakelaar onder spanning kan worden bediend_
| sterpuntsbehandeling
| <<local:Sterpuntsbehandeling,Sterpuntsbehandeling>> [1]
a| _manier waarop de sterpunt (punt waarop de gemeenschappelijke nuldraad van de drie fasen wordt aangesloten) van de transformator wordt behandeld om aardfouten te beheersen_

|===



.Relaties
[%autowidth.stretch]
|===
| Transformatoropstelling is ... | Omschrijving

| pass:[<span title="Maakt deel uit van de identificatie">🔑</span>&nbsp;]bij https://modellen.netbeheernederland.nl/aansluitingenregister#Overdrachtspunt[Overdrachtspunt] (Aansluitingenregister) [0..1 → 1]
a| 

|===









'''
[discrete]
== Waardelijsten


[[local:Eenheid-onregelmatigheid]]
[discrete]
=== Eenheid onregelmatigheid



[%autowidth.stretch]
|===
| Waarde | Omschrijving

| Hz
a| 
| kA
a| 
| p.u.
a| 
|===




[[local:Energiebron]]
[discrete]
=== Energiebron

.Zie ook
[%collapsible]
====
* bge:z=2025-05-08&g=2025-05-08[bge:z=2025-05-08&g=2025-05-08]
====

[%autowidth.stretch]
|===
| Waarde | Omschrijving

| biomassa
a| 
| gas
a| 
| kolen
a| 
| nucleair
a| 
| olie
a| 
| overig hernieuwbaar
a| 
| overig niet-hernieuwbaar
a| 
| water
a| 
| wind
a| 
| zon
a| 
|===




[[local:Energiedrager]]
[discrete]
=== Energiedrager



[%autowidth.stretch]
|===
| Waarde | Omschrijving

| elektriciteit
a| 
| gas
a| 
|===




[[local:Energieherkomst]]
[discrete]
=== Energieherkomst



[%autowidth.stretch]
|===
| Waarde | Omschrijving

| combinatie
a| 
| energienet
a| 
| installatie
a| 
|===




[[local:Hoogtereferentie]]
[discrete]
=== Hoogtereferentie



[%autowidth.stretch]
|===
| Waarde | Omschrijving

| maaiveld
a| _aardoppervlak inclusief bestrating en aardwerken zoals een talud of dijk, maar zonder vegetatie en bouwwerken zoals huizen en viaducten_
| NAP
a| _Normaal Amsterdams Pijl_
|===




[[local:Onregelmatigheid]]
[discrete]
=== Onregelmatigheid



[%autowidth.stretch]
|===
| Waarde | Omschrijving

| f<
a| _onderfrequentie_
| f>
a| _overfrequentie_
| I>
a| _lichte overstroom_
| I>>
a| _ernstige overstroom_
| U<
a| _onderspanning_
| U>
a| _overspanning_
|===




[[local:Regelbaarheid]]
[discrete]
=== Regelbaarheid



[%autowidth.stretch]
|===
| Waarde | Omschrijving

| continu regelbaar (online)
a| 
| spanningsloos instelbaar (offline)
a| 
|===




[[local:Soort-koppeling]]
[discrete]
=== Soort koppeling



[%autowidth.stretch]
|===
| Waarde | Omschrijving

| asynchroon
a| 
| direct drive
a| 
| dubbelgevoede inductiemachine
a| 
| omvormer-gekoppeld
a| 
| synchroon
a| 
|===




[[local:Sterpuntsbehandeling]]
[discrete]
=== Sterpuntsbehandeling



[%autowidth.stretch]
|===
| Waarde | Omschrijving

| geaard via impedantie
a| 
| hard geaard
a| 
| zwevend
a| 
|===




[[local:Type-elektriciteitsinstallatie-eenheid]]
[discrete]
=== Type elektriciteitsinstallatie-eenheid



[%autowidth.stretch]
|===
| Waarde | Omschrijving

| A
a| _overdrachtspunt beneden 110 kV en maximumcapaciteit minimaal 0,8 kW en beneden 1 MW_
| B
a| _overdrachtspunt beneden 110 kV en maximumcapaciteit minimaal 1 MW en beneden 50 MW_
| C
a| _overdrachtspunt beneden 110 kV en maximumcapaciteit minimaal 50 MW en beneden 60 MW_
| D
a| _overdrachtspunt minimaal 110 kV of maximumcapaciteit minimaal 60 MW_
|===

