name: Build documentation artifacts (development)
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python 3.12.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.7"
      - name: Install Poetry 2.0.1
        run: curl -sSL https://install.python-poetry.org | python3 - --version 2.0.1
      - name: Install Python project dependencies
        run: $HOME/.local/bin/poetry install --no-root
      - name: Install Just 1.38.0
        run: pip install rust-just==1.38.0
      - name: Generate documentation and schemas
        run: just generate-documentation
      - name: Commit artifacts to `docs-dev` branch
        run: |
          git fetch origin docs-dev
          git worktree add /tmp/docs-dev docs-dev

          rsync --exclude='.git' -av --delete artifacts/ /tmp/docs-dev/

          cd /tmp/docs-dev

          git config user.name "CICD"
          git config user.email "cicd@netbeheernederland.nl"

          git add --all
          git commit -m "Built artifacts" || echo "No changes to commit"
          git push origin docs-dev
